[profile.default]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [{ access = "read", path = "./"}]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = true
call_override = true

[profile.default.format]
report = "minimal"
